#!/bin/bash

usage()
{
  echo "Usage: $0 [ -h HOST:PORT:PASSWORD ] [ -i INVERVAL(sec) ] [ -o OUTPUT_FILE ]"
  exit 2
}

set_variable()
{
  local varname=$1
  shift
  if [ -z "${!varname}" ]; then
    eval "$varname=\"$@\""
  else
    echo "Error: $varname already set"
    usage
  fi
}

#########################
# Main script starts here

HOSTS=$FS_SESSIONS_HOSTS
OUTPUT_FILE=$FS_SESSIONS_OUTPUT_FILE
INTERVAL=$FS_SESSIONS_INTERVAL

while getopts 'h:i:o:?' c
do
  case $c in
    h) set_variable HOSTS $OPTARG ;;
    i) set_variable INTERVAL $OPTARG ;;
    o) set_variable OUTPUT_FILE $OPTARG ;;
    ?) usage ;; esac
done

[ -z "$HOSTS" ] && [ -z "$OUTPUT_FILE" ] && [ -z "$INVERVAL" ] && usage

while true
do
  RESULT=`fsesexe -h $HOSTS -x "show status" | grep "Sec out of max" | cut -d ' ' -f 1,8,13`
  index=0
  SESSIONS=()
  for v in $RESULT
  do
    SESSIONS[$index]=`echo $v | sed "s/,//"`
    let index=index+1
  done
  printf "`date +"%Y-%m-%d %H:%M:%S"`,%d,%d,%d\n" ${SESSIONS[0]} ${SESSIONS[1]} ${SESSIONS[2]} | tee -a $OUTPUT_FILE
  sleep $INTERVAL
done


